# Generated by Django 5.2.1 on 2025-06-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Educacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.BooleanField()),
                ('fechaCertificacion', models.DateTimeField()),
                ('visitante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Educacion.visitante')),
            ],
        ),
    ]
