# Generated by Django 5.2.1 on 2025-05-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('cuerpo', models.TextField()),
                ('imagenURL', models.TextField()),
                ('videoURL', models.TextField()),
                ('horasProximadas', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField()),
                ('idExamen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitulo', to='Examen.examen')),
            ],
        ),
    ]
