# Generated by Django 5.2.1 on 2025-05-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capitulo', '0002_documento_alter_capitulo_cuerpo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
