# Generated by Django 5.2.1 on 2025-05-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capitulo', '0003_delete_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='idExamen',
        ),
    ]
