# Generated by Django 5.2.1 on 2025-05-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capitulo', '0005_capitulo_activacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='activacion',
            field=models.IntegerField(default=10),
        ),
    ]
