# Generated by Django 5.2.1 on 2025-05-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capitulo', '0006_alter_capitulo_activacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='orden',
            field=models.IntegerField(unique=True),
        ),
    ]
