# Generated by Django 5.2.1 on 2025-06-21 18:59

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('imagenURL', models.TextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('fechaCreacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
