# Generated by Django 5.2.1 on 2025-06-18 15:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='La Cooperativa tiene como misión apoyar y promover el desarrollo social e integral de sus cooperados, por medio de la democratización del crédito en los segmentos productivos, rurales y urbanos marginales, brindando confianza y seguridad, con eficiencia, honestidad, responsabilidad, calidad y carisma Salesiano.'),
        ),
    ]
