# Generated by Django 5.2.1 on 2025-06-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mision', '0002_alter_mision_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='titulo',
            field=models.CharField(default='Misión', max_length=100),
        ),
    ]
