# Generated by Django 5.2.1 on 2025-05-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capitulo', '0004_remove_capitulo_idexamen'),
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='capitulo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='Capitulo.capitulo'),
        ),
    ]
