# Generated by Django 5.2.1 on 2025-06-07 19:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagenURL', models.TextField()),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('fechaCreacion', models.DateTimeField()),
                ('referenciaURL', models.TextField()),
            ],
        ),
    ]
