# Generated by Django 5.2.1 on 2025-06-19 22:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Valores', max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField(default='Aquí van los valores institucionales...')),
            ],
        ),
    ]
