# Generated by Django 5.2.1 on 2025-05-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('email', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('nombreCompleto', models.CharField(max_length=1000)),
                ('ultimoAcceso', models.DateTimeField()),
            ],
        ),
    ]
