# Generated by Django 5.2.1 on 2025-05-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Capitulo', '0004_remove_capitulo_idexamen'),
        ('Educacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aprobado', models.BooleanField(default=True)),
                ('fechaProgreso', models.DateTimeField()),
                ('capitulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capitulo', to='Capitulo.capitulo')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='Educacion.visitante')),
            ],
        ),
    ]
