# Generated by Django 5.2.1 on 2025-06-19 21:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Visión', max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField(default='Nuestra visión es ser una cooperativa líder que transforma vidas con valores Salesianos.')),
            ],
        ),
    ]
